### ISSUE TITLE
Color Not Matching Swatch

### ISSUE THREAD

**Issue by ddhhz** [fcanas/ios-color-picker#7]
Hi there, I tried to use your library in Swift. Color in the circle doesn't seem to be matching the swatch and the swatch seems to have been flipped. Have you encountered this issue?  Thanks!!

![image](https://cloud.githubusercontent.com/assets/5880908/9866985/49bab612-5b37-11e5-9f33-8dfdd3f23d05.png)
![image](https://cloud.githubusercontent.com/assets/5880908/9867043/604de46c-5b37-11e5-9d28-2effbdae43cc.png)
![image](https://cloud.githubusercontent.com/assets/5880908/9867049/6aac80ee-5b37-11e5-92b5-1b4209aa55e0.png)

**Comment by fcanas** [comment]
@ddhhz Wow. I have not encountered this issue before. How are you including the color picker? The swatch looks completely wrong -- it's not supposed to have the black gradient. We might have to dig through a few more details of your particular usage to figure out what went wrong.

**Comment by ddhhz** [comment]
@fcanas Thanks for your quick response. This is literally everything

![image](https://cloud.githubusercontent.com/assets/5880908/9867474/35c085a6-5b3c-11e5-91b8-5d81bb732d1f.png)

![image](https://cloud.githubusercontent.com/assets/5880908/9867470/2ed12dd6-5b3c-11e5-8e16-26c352453f32.png)

**Comment by ddhhz** [comment]
I will do a bit more digging tomorrow and perhaps upload a test project.

**Comment by fcanas** [comment]
That would be excellent.

I created a new Swift target in the example project on a new branch and it does not exhibit this problem: 
https://github.com/fcanas/ios-color-picker/tree/swift-example

In case it was an issue with frameworks, I made a branch with no frameworks and an Objective-C bridging header, and that didn't exhibit the problem either.
https://github.com/fcanas/ios-color-picker/tree/swift-no-frameworks

One issue I did encounter is when including the color picker via a framework, instantiating the view controller fails because it's not looking for its xib in the correct bundle. I've fixes that now in 4f2a44e90074376c5cfe008667fb8444fd915d72

That fix makes me want to make a patch release soon. Please let me know what you find when you dig into your problem.

**Comment by ddhhz** [comment]
I tried swapping it out with one of my images, it shows up correctly. Tried to use xcassets, works fine. Removed all Pods and pod install -> fixed. So sorry to waste your time. It must be my xcode ; |

**Comment by fcanas** [comment]
My best guess is that you had a similar, but different image with the same name as the asset this library uses. If it's not that, I have no idea.

Thank you for bringing this up, because it brought #8 to my attention. Definitely not a waste of time :confetti_ball:

**Comment by ddhhz** [comment]
= D. Nope I didn't have any image like that in my project. Must be xCode being dumb. Thanks for all your good work.
